-- Econ_Global
-- Author: FramedArchitecture
-- DateCreated: 5/5/2015
--------------------------------------------------------------
IsGNK = ContentManager.IsActive("0E3751A1-F840-4e1b-9706-519BF484E59D", ContentType.GAMEPLAY)
IsBNW = ContentManager.IsActive("6DA07636-4123-4018-B643-6575B4EC336B", ContentType.GAMEPLAY)
IsHEALTHMOD = GameInfo.Yields["YIELD_HEALTH"] and true or false 
BASE_DEBT_TERM = GameInfo.GameSpeeds[PreGame.GetGameSpeed()].DealDuration
BASE_MAX_DEBT = 1000
BASE_MIN_DEBT = 100
BASE_UNEMPLOYMENT_RATE = 0.05
BASE_INTEREST_RATE = 0.08
MAX_INTEREST_RATE = 0.33
MIN_INTEREST_RATE = 0.03
DEBT_RATIO_THRESHOLD = 0.25
BASE_TAX_RATE = 0.05
BASE_REVENUE_DIVISOR = 51
BASE_EXPENSE_RATE = 0.01
BASE_TAX_ERA = GameInfoTypes.ERA_CLASSICAL
BASE_DEBT_ERA = GameInfoTypes.ERA_RENAISSANCE
BASE_MARKETS_ERA = GameInfoTypes.ERA_RENAISSANCE
EXPANDED_TAX_ERA = GameInfoTypes.ERA_INDUSTRIAL
BASE_EVENT_ERA = GameInfoTypes.ERA_INDUSTRIAL
BRANCH_COMMERCE = GameInfoTypes.POLICY_BRANCH_COMMERCE
BRANCH_FREEDOM = GameInfoTypes.POLICY_BRANCH_FREEDOM
BRANCH_ORDER = GameInfoTypes.POLICY_BRANCH_ORDER
BRANCH_AUTOCRACY = GameInfoTypes.POLICY_BRANCH_AUTOCRACY
YIELD_PRODUCTION = YieldTypes.YIELD_PRODUCTION
YIELD_GOLD = YieldTypes.YIELD_GOLD
PRODUCTION_MOD = 11
PURCHASE_DIVISOR = 2.4
TRADE_MOD = 17
POLITICAL_CAPITAL_MOD = 1.9
POPULATION_MULTIPLIER = 55
POPULATION_CITY_MULTIPLIER = 0.85
BASE_WORLD_SIZE = GameInfo.Worlds[PreGame.GetWorldSize()].DefaultPlayers
MAX_BORDERS_BONUS = 5
MAX_TAX_RATE = 0.75
MIN_TAX_RATE = 0.02
TAX_GDP_THRESHOLD = 0.45
AI_ACTION_THRESHOLD = 6
AI_TAX_DECREMENT = 0.01
AI_BASE_TAX_INCREMENTS = 5
AI_INIT_LOAN_PERCENT = 0.10
AI_BASE_DEBT_RATIO = 0.12
AI_BASE_DEBT_RESISTANCE = 83
AI_POLITICAL_THRESHOLD = -6
AI_POLICY_RESISTANCE = 33
AI_POLICY_WEIGHT = 4
AI_RATE_THRESHOLD = 0.11
AI_DEBT_TAX_RATIO = (0.75*MAX_TAX_RATE)
AI_MIN_DEBT_PAYMENT = 30
POLICY_COOLDOWN = math.ceil(3 + BASE_DEBT_TERM/10)
GROWTH_BOOM = 0.15
GROWTH_EXPANSION = 0.05
GROWTH_STABLE = 0.01
GROWTH_STAGNATION = -0.05
GROWTH_RECESSION = -0.15
GROWTH_BUST = -0.25
BASE_EVENT_TURNS = 3
BASE_EVENT_UNEMPLOYED = 0.10
BASE_EVENT_CHANCE = 30
MIN_EVENT_MALUS = 10
MED_EVENT_MALUS = 25
MAX_EVENT_MALUS = 50
BULL_MARKET = 10
BEAR_MARKET = -10
GAME_MAX_ERAS = 0

for row in GameInfo.Eras() do
	GAME_MAX_ERAS = GAME_MAX_ERAS + 1
end